"""No-code builder: schema validation, indicator math, and one execution path through the runner."""
from __future__ import annotations

import copy
import json
import os
import unittest

from app.errors import ValidationFailed
from app.sandbox.nocode import compile_spec, validate_spec
from app.sandbox.runner import run_series, run_signal
from app.sandbox.validate import validate_source

DAY = 86_400_000
EXAMPLE = os.path.join(os.path.dirname(__file__), "..", "..", "docs", "examples", "strategies", "nocode_ema_cross_hype.json")

BASE = {
    "markets": ["BTC"], "timeframe": "1d", "lookback": 60, "max_leverage": 2,
    "indicators": {"fast": {"type": "sma", "source": "close", "period": 3},
                   "slow": {"type": "sma", "source": "close", "period": 10}},
    "rules": [{"when": {"all": [{"left": "fast", "op": ">", "right": "slow"}]}, "weight": 1.5}],
    "default_weight": -0.5,
}


def series(closes, coin="BTC", spread=1.0):
    return {coin: [{"t": i * DAY, "o": c, "h": c + spread, "l": c - spread, "c": c, "v": 1.0} for i, c in enumerate(closes)]}


def helpers(src: str) -> dict:
    """Exec OUR generated source in-process (trusted test context) to unit-test the embedded indicator code."""
    ns: dict = {}
    exec(compile(src, "<generated>", "exec"), ns)  # noqa: S102 - generated by us, test only
    return ns


class SchemaTests(unittest.TestCase):
    def errs(self, **patch):
        spec = copy.deepcopy(BASE)
        for k, v in patch.items():
            if v is None:
                spec.pop(k, None)
            else:
                spec[k] = v
        return validate_spec(spec)

    def paths(self, errs):
        return [e["path"] for e in errs]

    def test_valid(self):
        self.assertEqual(validate_spec(BASE), [])

    def test_example_file(self):
        with open(EXAMPLE, encoding="utf-8") as fh:
            spec = json.load(fh)
        self.assertEqual(validate_spec(spec), [])
        self.assertTrue(validate_source(compile_spec(spec)).ok)

    def test_errors_have_paths(self):
        cases = [
            (dict(markets=None), "markets"), (dict(markets=["BTC'); import os #"]), "markets[0]"),
            (dict(timeframe="5m"), "timeframe"), (dict(lookback=10), "lookback"),
            (dict(max_leverage=51), "max_leverage"), (dict(bogus=1), "bogus"),
            (dict(indicators={"a'b": {"type": "sma", "period": 3}}), "indicators.a'b"),
            (dict(indicators={"__class__": {"type": "sma", "period": 3}}), "indicators.__class__"),
            (dict(indicators={"x": {"type": "macd", "period": 3}}), "indicators.x.type"),
            (dict(indicators={"x": {"type": "sma", "period": 0}}), "indicators.x.period"),
            (dict(indicators={"x": {"type": "sma", "period": 3, "source": "vwap"}}), "indicators.x.source"),
            (dict(indicators={"x": {"type": "atr", "period": 3, "source": "close"}}), "indicators.x.source"),
            (dict(indicators={"x": {"type": "sma", "period": 59}}), "indicators.x"),
            (dict(indicators={"close": {"type": "sma", "period": 3}}), "indicators.close"),
            (dict(rules=[]), "rules"),
            (dict(rules=[{"when": {"all": [{"left": "nope", "op": ">", "right": 1}]}, "weight": 1}]), "rules[0].when.all[0].left"),
            (dict(rules=[{"when": {"all": [{"left": "fast", "op": "==", "right": 1}]}, "weight": 1}]), "rules[0].when.all[0].op"),
            (dict(rules=[{"when": {"all": [{"left": 1, "op": ">", "right": 2}]}, "weight": 1}]), "rules[0].when.all[0]"),
            (dict(rules=[{"when": {"xor": []}, "weight": 1}]), "rules[0].when"),
            (dict(rules=[{"when": {"all": [{"left": "fast", "op": ">", "right": float("nan")}]}, "weight": 1}]), "rules[0].when.all[0].right"),
            (dict(rules=[{"when": {"all": [{"left": "fast", "op": ">", "right": 1}]}, "weight": 3}]), "rules"),
            (dict(rules=[{"when": {"all": [{"left": "fast", "op": ">", "right": 1}]}, "weight": True}]), "rules[0].weight"),
            (dict(default_weight="1"), "default_weight"),
        ]
        for patch, path in cases:
            with self.subTest(patch=patch):
                self.assertIn(path, self.paths(self.errs(**patch)))

    def test_multi_market_gross_limit(self):
        e = self.errs(markets=["BTC", "SOL"])  # 2 × 1.5 > 2
        self.assertTrue(any("markets" in x["message"] for x in e), e)
        self.assertEqual(self.errs(markets=["BTC", "SOL"], default_weight=0,
                                   rules=[{"when": {"all": [{"left": "fast", "op": ">", "right": "slow"}]}, "weight": 1}]), [])

    def test_nesting_depth(self):
        cond = {"left": "fast", "op": ">", "right": 1}
        deep = {"all": [{"any": [{"all": [{"any": [cond]}]}]}]}
        e = self.errs(rules=[{"when": deep, "weight": 1}])
        self.assertTrue(any("nesting" in x["message"] for x in e), e)

    def test_compile_raises_structured(self):
        bad = copy.deepcopy(BASE)
        bad["timeframe"] = "2d"
        with self.assertRaises(ValidationFailed) as cm:
            compile_spec(bad)
        self.assertEqual(cm.exception.details["errors"][0]["path"], "timeframe")

    def test_non_object(self):
        self.assertTrue(validate_spec([1, 2]))
        self.assertTrue(validate_spec(None))


class IndicatorMathTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.ns = helpers(compile_spec(BASE))

    def test_sma_ema(self):
        self.assertEqual(self.ns["_sma"]([1, 2, 3, 4], 2), [None, 1.5, 2.5, 3.5])
        e = self.ns["_ema"]([1.0, 2.0, 3.0, 4.0], 2)
        self.assertEqual(e[:2], [None, 1.5])
        self.assertAlmostEqual(e[2], 3 * (2 / 3) + 1.5 * (1 / 3))

    def test_rsi_extremes(self):
        up = self.ns["_rsi"]([float(i) for i in range(30)], 14)
        down = self.ns["_rsi"]([float(30 - i) for i in range(30)], 14)
        flat = self.ns["_rsi"]([5.0] * 30, 14)
        self.assertEqual(up[-1], 100.0)
        self.assertEqual(down[-1], 0.0)
        self.assertEqual(flat[-1], 50.0)
        self.assertIsNone(up[13])
        self.assertIsNotNone(up[14])

    def test_atr_highest_lowest_roc(self):
        rows = [{"o": 10.0, "h": 11.0, "l": 9.0, "c": 10.0}] * 20
        self.assertAlmostEqual(self.ns["_atr"](rows, 5)[-1], 2.0)
        self.assertEqual(self.ns["_window"]([1, 5, 2, 4], 2, max), [None, 5, 5, 4])
        self.assertEqual(self.ns["_window"]([1, 5, 2, 4], 3, min), [None, None, 1, 2])
        self.assertAlmostEqual(self.ns["_roc"]([100.0, 110.0, 121.0], 1)[-1], 10.0)

    def test_shift(self):
        s = self.ns["_series"]([{"c": float(i), "h": float(i), "l": 0.0, "o": 0.0, "v": 0.0} for i in range(6)], ("highest", "high", 2, 1))
        self.assertEqual(s, [None, None, 1.0, 2.0, 3.0, 4.0])


class ExecutionTests(unittest.TestCase):
    def test_trend_rule_runs_in_sandbox(self):
        src = compile_spec(BASE)
        self.assertEqual(run_signal(src, series([10.0 + i for i in range(80)])).weights, {"BTC": 1.5})
        self.assertEqual(run_signal(src, series([float(100 - i) for i in range(80)])).weights, {"BTC": -0.5})

    def test_first_matching_rule_wins_and_price_operand(self):
        spec = copy.deepcopy(BASE)
        spec["rules"] = [
            {"when": {"all": [{"left": "close", "op": ">", "right": 1000}]}, "weight": 2},
            {"when": {"any": [{"left": "close", "op": ">", "right": 50}]}, "weight": 1},
            {"when": {"any": [{"left": "close", "op": ">", "right": 10}]}, "weight": 0.5},
        ]
        src = compile_spec(spec)
        self.assertEqual(run_signal(src, series([60.0] * 80)).weights, {"BTC": 1.0})

    def test_crosses_above_fires_only_on_cross_bar(self):
        spec = copy.deepcopy(BASE)
        spec["default_weight"] = 0
        spec["rules"] = [{"when": {"all": [{"left": "close", "op": "crosses_above", "right": 100}]}, "weight": 1}]
        closes = [90.0] * 70 + [110.0] * 10          # crosses at index 70
        res = run_series(compile_spec(spec), series(closes))
        fired = [s.index for s in res.steps if s.weights["BTC"] == 1.0]
        self.assertEqual(fired, [70])

    def test_crosses_below_with_breakout_indicator(self):
        spec = copy.deepcopy(BASE)
        spec["default_weight"] = 0
        spec["indicators"] = {"lo": {"type": "lowest", "source": "low", "period": 5, "shift": 1}}
        spec["rules"] = [{"when": {"all": [{"left": "close", "op": "<", "right": "lo"}]}, "weight": -1}]
        closes = [100.0] * 75 + [80.0] * 5
        res = run_series(compile_spec(spec), series(closes, spread=0.0))
        self.assertEqual([s.index for s in res.steps if s.weights["BTC"] == -1.0], [75])

    def test_example_runs(self):
        with open(EXAMPLE, encoding="utf-8") as fh:
            spec = json.load(fh)
        src = compile_spec(spec)
        closes = [100 + (i % 37) * 1.5 - (i % 11) for i in range(260)]
        res = run_series(src, series(closes, coin="HYPE"))
        self.assertTrue(all(s.weights["HYPE"] in (0.0, 0.5, 1.0) for s in res.steps))


if __name__ == "__main__":
    unittest.main()
