-- =====================================================================================================
-- 0016_executor_keygen.sql — agent private keys are GENERATED BY THE EXECUTOR ONLY
-- (docs/security/REVIEW_WEB_INFRA.md H1 residual: "a compromised api can create an agent key it KNOWS, seal it with
-- its encrypt-only KMS role, and the executor attests it — attestation only proves the executor can open it").
-- Runs as app_migrator (owner). No BEGIN/COMMIT (migrate.py wraps each file in one transaction).
--
-- New flow
--   POST /v1/agents (api)           INSERT a REQUEST row: (user_id, master_address, agent_name, status 'requested') —
--                                   no agent_address, no key_ciphertext, no kms_key_version. The api role holds
--                                   column-level INSERT on exactly those four columns and NO INSERT/UPDATE privilege
--                                   on agent_address / key_ciphertext / kms_key_version / keygen_at.
--   executor (attest-agents job every minute + every tick; app/execution/trust_jobs.generate_agents)
--                                   generates the secp256k1 key IN THE EXECUTOR, seals it under the agent-keys KMS key
--                                   (executor: encrypt + decrypt; the api has NO role on agent-keys any more), re-opens
--                                   the sealed blob to prove it derives the address, KMS-signs the attestation, and
--                                   writes agent_address + key_ciphertext + kms_key_version + keygen_at ONCE
--                                   (status requested → pending_approval, trigger below).
--   GET /v1/agents/{id} (api)       the browser polls until agent_address + attestation are present.
--
-- Enforcement (in addition to the column privileges):
--   * agent_keys_guard trigger (replaces 0013's agent_keys_attestation_guard function body, same trigger):
--       - INSERT: a key-less row must be status 'requested'; a 'requested' row cannot carry key material; attestation
--         columns are never insertable (0013 rule kept).
--       - key material (agent_address, key_ciphertext, kms_key_version, keygen_at) is written exactly once, all four
--         together, only on the transition requested → pending_approval; immutable afterwards (0013 rule kept).
--       - user_id / master_address / agent_name immutable.
--       - an attestation can only be written on an executor-generated key (keygen_at NOT NULL), once (0013 rule kept).
--       - revoked / rotated / expired are terminal; 'requested' may only become pending_approval (with a key) or
--         revoked; a row can only become 'active' if its key was generated by the executor (keygen_at NOT NULL).
--   * one live agent per master now also counts requests (index predicate: status NOT IN terminal statuses).
--
-- Legacy rows (keys generated by the api before this migration, keygen_at NULL): 'pending_approval' ones are revoked
-- here (the user creates a new agent; the browser never signs ApproveAgent for them: they can no longer be attested —
-- the attestation message is now "aijalon-agent-v2|…", signed only for executor-generated keys). 'active' ones keep
-- trading; rotate them (POST /v1/agents rotate=true) to move every user onto an executor-generated key (RUNBOOK).
--
-- NOTE (PostgreSQL): a value added by ALTER TYPE … ADD VALUE cannot be USED in the same transaction, so nothing below
-- spells the literal 'requested' as an enum value: CHECKs and the index use the committed values, and the trigger
-- compares status::text (evaluated at run time, after this migration committed).
-- =====================================================================================================

ALTER TYPE agent_key_status ADD VALUE IF NOT EXISTS 'requested';

-- ---------------------------------------------------------------- columns
ALTER TABLE agent_keys ALTER COLUMN agent_address   DROP NOT NULL;
ALTER TABLE agent_keys ALTER COLUMN key_ciphertext  DROP NOT NULL;
ALTER TABLE agent_keys ALTER COLUMN kms_key_version DROP NOT NULL;
ALTER TABLE agent_keys ADD COLUMN IF NOT EXISTS keygen_at timestamptz;   -- set by the executor when it generated the key

DO $$ BEGIN
  ALTER TABLE agent_keys ADD CONSTRAINT agent_keys_key_material_shape CHECK (
        (agent_address IS NULL AND key_ciphertext IS NULL AND kms_key_version IS NULL AND keygen_at IS NULL)
     OR (agent_address IS NOT NULL AND key_ciphertext IS NOT NULL AND kms_key_version IS NOT NULL));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- no key → only a request or a request that was withdrawn ('revoked'); every other status needs a key
DO $$ BEGIN
  ALTER TABLE agent_keys ADD CONSTRAINT agent_keys_keyless_status CHECK (
        key_ciphertext IS NOT NULL OR status NOT IN ('pending_approval', 'active', 'rotated', 'expired'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE agent_keys ADD CONSTRAINT agent_keys_attestation_needs_key CHECK (
        attestation_sig IS NULL OR key_ciphertext IS NOT NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------- one live agent (or request) per master
DROP INDEX IF EXISTS agent_keys_one_live_per_master;
CREATE UNIQUE INDEX agent_keys_one_live_per_master ON agent_keys (master_address)
    WHERE status NOT IN ('revoked', 'rotated', 'expired');

-- the executor's key-generation queue (requests: no key, not withdrawn, not failed)
CREATE INDEX IF NOT EXISTS agent_keys_keygen_todo_idx ON agent_keys (created_at)
    WHERE key_ciphertext IS NULL AND attestation_failed_at IS NULL AND status NOT IN ('revoked', 'rotated', 'expired');

-- ---------------------------------------------------------------- guard trigger (replaces the 0013 body)
CREATE OR REPLACE FUNCTION agent_keys_attestation_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  old_s text;
  new_s text := NEW.status::text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.attestation_sig IS NOT NULL OR NEW.attestation_key_version IS NOT NULL OR NEW.attested_at IS NOT NULL
       OR NEW.attestation_failed_at IS NOT NULL OR NEW.attestation_error IS NOT NULL THEN
      RAISE EXCEPTION 'agent_keys: attestation columns are written only by the executor attestation job'
        USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.key_ciphertext IS NULL AND new_s <> 'requested' THEN
      RAISE EXCEPTION 'agent_keys: a row without key material must be an agent request (status requested)'
        USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.key_ciphertext IS NOT NULL AND new_s = 'requested' THEN
      RAISE EXCEPTION 'agent_keys: an agent request cannot carry key material (the executor generates the key)'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  old_s := OLD.status::text;

  -- attestation: once, never changed (0013), and only over a key the EXECUTOR generated
  IF OLD.attestation_sig IS NOT NULL AND (
       NEW.attestation_sig IS DISTINCT FROM OLD.attestation_sig
    OR NEW.attestation_key_version IS DISTINCT FROM OLD.attestation_key_version
    OR NEW.attested_at IS DISTINCT FROM OLD.attested_at) THEN
    RAISE EXCEPTION 'agent_keys: an attestation is immutable once written' USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.attestation_sig IS NOT NULL AND OLD.attestation_sig IS NULL AND NEW.keygen_at IS NULL THEN
    RAISE EXCEPTION 'agent_keys: only an executor-generated key can be attested' USING ERRCODE = 'check_violation';
  END IF;

  -- identity
  IF NEW.user_id IS DISTINCT FROM OLD.user_id OR NEW.master_address IS DISTINCT FROM OLD.master_address
     OR NEW.agent_name IS DISTINCT FROM OLD.agent_name THEN
    RAISE EXCEPTION 'agent_keys: identity and key material are immutable' USING ERRCODE = 'check_violation';
  END IF;

  -- key material: written once by the executor (requested → pending_approval), immutable afterwards
  IF OLD.key_ciphertext IS NOT NULL OR OLD.agent_address IS NOT NULL THEN
    IF NEW.agent_address IS DISTINCT FROM OLD.agent_address OR NEW.key_ciphertext IS DISTINCT FROM OLD.key_ciphertext
       OR NEW.kms_key_version IS DISTINCT FROM OLD.kms_key_version OR NEW.keygen_at IS DISTINCT FROM OLD.keygen_at THEN
      RAISE EXCEPTION 'agent_keys: identity and key material are immutable' USING ERRCODE = 'check_violation';
    END IF;
  ELSIF NEW.key_ciphertext IS NOT NULL OR NEW.agent_address IS NOT NULL OR NEW.kms_key_version IS NOT NULL
        OR NEW.keygen_at IS NOT NULL THEN
    IF old_s <> 'requested' OR new_s <> 'pending_approval' OR NEW.key_ciphertext IS NULL
       OR NEW.agent_address IS NULL OR NEW.kms_key_version IS NULL OR NEW.keygen_at IS NULL THEN
      RAISE EXCEPTION 'agent_keys: key material is written once, all together, on requested -> pending_approval'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  -- status machine
  IF new_s IS DISTINCT FROM old_s THEN
    IF old_s IN ('revoked', 'rotated', 'expired') THEN
      RAISE EXCEPTION 'agent_keys: % is a terminal status', old_s USING ERRCODE = 'check_violation';
    END IF;
    IF old_s = 'requested' AND new_s NOT IN ('pending_approval', 'revoked') THEN
      RAISE EXCEPTION 'agent_keys: an agent request can only become pending_approval or revoked'
        USING ERRCODE = 'check_violation';
    END IF;
    IF new_s = 'requested' THEN
      RAISE EXCEPTION 'agent_keys: a row cannot go back to requested' USING ERRCODE = 'check_violation';
    END IF;
    IF new_s = 'active' AND NEW.keygen_at IS NULL THEN
      RAISE EXCEPTION 'agent_keys: only an executor-generated agent key can be activated'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS agent_keys_attestation_guard ON agent_keys;
CREATE TRIGGER agent_keys_attestation_guard BEFORE INSERT OR UPDATE ON agent_keys
    FOR EACH ROW EXECUTE FUNCTION agent_keys_attestation_guard();

-- ---------------------------------------------------------------- privileges
-- app_api: requests only. Table-level INSERT (0002) is replaced by column-level INSERT on the request columns, so an
-- INSERT naming agent_address / key_ciphertext / kms_key_version / keygen_at fails with insufficient_privilege.
REVOKE INSERT ON agent_keys FROM app_api;
REVOKE INSERT (agent_address, key_ciphertext, kms_key_version, keygen_at) ON agent_keys FROM app_api;
REVOKE UPDATE (agent_address, key_ciphertext, kms_key_version, keygen_at) ON agent_keys FROM app_api;
GRANT INSERT (user_id, master_address, agent_name, status) ON agent_keys TO app_api;
GRANT SELECT (keygen_at) ON agent_keys TO app_api;
-- app_executor: writes the key material once (trigger) — still no INSERT and no DELETE on agent_keys.
GRANT UPDATE (agent_address, key_ciphertext, kms_key_version, keygen_at) ON agent_keys TO app_executor;

-- ---------------------------------------------------------------- legacy (api-generated) keys
-- Pending approvals of api-generated keys are withdrawn: the user creates a new (executor-generated) agent.
UPDATE agent_keys SET status = 'revoked', revoked_at = coalesce(revoked_at, now())
 WHERE status = 'pending_approval' AND keygen_at IS NULL;
