#!/usr/bin/env node
// Generate (or --check) web/sri.json: Subresource Integrity hashes for the pinned Firebase JS SDK (SECURITY M2).
//
//   node web/tools/gen-sri.mjs            download + hash, write web/sri.json      (make sri)
//   node web/tools/gen-sri.mjs --check    download + hash, compare with web/sri.json, exit 1 on any difference
//
// NEEDS NETWORK (https://www.gstatic.com). The authoring/CI-agent sandbox has none: the owner's LOCAL session runs
// `make sri`, reviews the diff and commits web/sri.json (DEPLOY.md §3). Production builds (web/build.mjs with
// APP_CONFIG) refuse to build without it; the deploy's CSP then includes the import map's hash (`make csp-sync`).
//
// It starts from firebase-app.js and firebase-auth.js at https://www.gstatic.com/firebasejs/<firebaseSdkVersion>/
// (web/public/app-config.json), follows every static/dynamic ES-module import with a literal specifier, and hashes
// each module (sha384). An import that leaves that versioned directory aborts the run: the CSP and the import map
// only cover the pinned path.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const WEB = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(WEB, "sri.json");
const version = String(JSON.parse(readFileSync(join(WEB, "public", "app-config.json"), "utf8")).firebaseSdkVersion || "");
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error("app-config.json firebaseSdkVersion must be x.y.z");
  process.exit(2);
}
const BASE = `https://www.gstatic.com/firebasejs/${version}/`;
const IMPORT_RE = /\b(?:import|export)\s*(?:[\w*{}\s,$]+?\s*from\s*)?["']([^"']+)["']|\bimport\s*\(\s*["']([^"']+)["']\s*\)/g;

async function get(url) {
  const res = await fetch(url, { redirect: "error" });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const ct = res.headers.get("content-type") || "";
  if (!/javascript/i.test(ct)) throw new Error(`${url}: unexpected content-type ${ct}`);
  return Buffer.from(await res.arrayBuffer());
}

const hashes = {};
const queue = ["firebase-app.js", "firebase-auth.js"];
while (queue.length) {
  const name = queue.shift();
  if (name in hashes) continue;
  const body = await get(BASE + name);
  hashes[name] = "sha384-" + createHash("sha384").update(body).digest("base64");
  const src = body.toString("utf8");
  for (const m of src.matchAll(IMPORT_RE)) {
    const spec = m[1] ?? m[2];
    if (!spec) continue;
    const abs = new URL(spec, BASE + name).href;
    if (!abs.startsWith(BASE)) throw new Error(`${name} imports ${abs}, outside the pinned ${BASE} — not covered by the CSP/SRI`);
    const rel = abs.slice(BASE.length);
    if (!/^[a-z0-9][a-z0-9._/-]*\.js$/.test(rel) || rel.includes("..")) throw new Error(`unexpected module path ${rel}`);
    if (!(rel in hashes) && !queue.includes(rel)) queue.push(rel);
  }
}
const out = { version, ...Object.fromEntries(Object.entries(hashes).sort(([a], [b]) => a.localeCompare(b))) };

if (process.argv.includes("--check")) {
  if (!existsSync(OUT)) {
    console.error("web/sri.json missing (run make sri)");
    process.exit(1);
  }
  const cur = JSON.parse(readFileSync(OUT, "utf8"));
  const bad = Object.keys({ ...cur, ...out }).filter((k) => !k.startsWith("_") && cur[k] !== out[k]);
  if (bad.length) {
    console.error(`web/sri.json differs from the live SDK for: ${bad.join(", ")} — investigate before regenerating`);
    process.exit(1);
  }
  console.log(`web/sri.json matches ${Object.keys(hashes).length} live module(s) of Firebase ${version}`);
} else {
  writeFileSync(OUT, JSON.stringify({ _comment: `generated by web/tools/gen-sri.mjs ${new Date().toISOString()} — review the diff, then commit`, ...out }, null, 2) + "\n");
  console.log(`wrote web/sri.json (${Object.keys(hashes).length} module(s)): ${Object.keys(hashes).join(", ")}`);
}
